spring:
  jpa:
    #    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
    #      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: whatever
    driverClassName: org.postgresql.Driver